spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
    datasource:
        url: jdbc:postgresql://localhost:5432/wedding
        username: postgres
        password: mysecretpassword
server:
    port: 8081
