version: '3.3'
services:
  wedding-app:
    image: gdefofot/springboot-angular-wedding-app:16.3.2023.21.48.6
    ports:
      - "8090:8080"
    restart: "always"
    environment:
       SPRING_PROFILES_ACTIVE: dev
       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: mysecretpassword

  postgres:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
volumes:
  db-data: