name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  POSTGRESQL_DB: wedding
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: mysecretpassword
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin
  #SPRING_DATASOURCE_URL: 'jdbc:postgresql://localhost:5432/postgres'
  #SPRING_DATASOURCE_USERNAME: postgres
  #SPRING_DATASOURCE_PASSWORD: mysecretpassword

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Build and push
        run: |
          set +x
          echo "deploy postgres"
          docker network create wedding-network
          docker run -d --name postgres -e POSTGRES_DB=${{ env.POSTGRESQL_DB }} -e POSTGRES_USER=${{ env.POSTGRESQL_USER }} -e  POSTGRES_PASSWORD=${{ env.POSTGRESQL_PASSWORD }} --network=wedding-network postgres:12
          sleep 5
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/wedding:latest --network=wedding-network .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wedding:latest
      
